spring.application.name=enformaplus

# A porta padrão já é 8080, mas se quiser colocar outra, é só alterar o valor
server.port=8080

# Configuração do Banco de dados H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true