spring.application.name=enformaplus

# A porta padrão já é 8080, mas se quiser colocar outra, é só alterar o valor
server.port=8080

# Configuração do mySQL no docker
spring.datasource.url=jdbc:mysql://localhost:3306/diademaEnforma
spring.datasource.username=admin
spring.datasource.password=enforma
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
